# Generated by Django 4.2.3 on 2025-02-01 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_message_sender_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operator',
            options={'verbose_name': 'Operator', 'verbose_name_plural': 'Operators'},
        ),
        migrations.AlterModelOptions(
            name='userdetails',
            options={'verbose_name': 'Guest', 'verbose_name_plural': 'Guests'},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='connect_type',
        ),
    ]
