# Generated by Django 4.2.3 on 2025-02-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_operator_options_alter_userdetails_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_uuid',
            field=models.UUIDField(default=11111, unique=True, verbose_name='Ticket UUID'),
            preserve_default=False,
        ),
    ]
