# Generated by Django 4.2.3 on 2025-02-01 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_message_sender_operator_alter_ticket_operator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender_user',
            new_name='sender_guest',
        ),
    ]
