# Generated by Django 4.2.3 on 2025-02-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_rename_sender_user_message_sender_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=10),
        ),
    ]
