# Generated by Django 4.2.3 on 2025-02-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_userdetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='location',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
